### ISSUE TITLE
3.2 Compatibility

### ISSUE THREAD

**Issue by nglasl** [camfindlay/silverstripe-wordpressimport#17]
When viewing a blog holder, the import tab displays a page not found because the following controller URL can no longer be accessed directly.

https://github.com/camfindlay/silverstripe-wordpressimport/blob/master/code/WpImporter.php#L12

This was my temporary workaround, but obviously this should have a better name :)

```yaml
Director:
  rules:
    'WpImporter_Controller': 'WpImporter_Controller'
```
